// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Base/Footer.vue')['default']
    HaveATry: typeof import('./src/components/Home/HaveATry.vue')['default']
    IntroCard: typeof import('./src/components/Home/IntroCard.vue')['default']
    MineCard: typeof import('./src/components/Mine/MineCard.vue')['default']
    MineInfo: typeof import('./src/components/Mine/MineInfo.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard/ProductCard.vue')['default']
    ProductCardCol: typeof import('./src/components/ProductCard/ProductCardCol.vue')['default']
    ProductListView: typeof import('./src/components/Products/ProductListView.vue')['default']
    ProductRowView: typeof import('./src/components/Products/ProductRowView.vue')['default']
    RadioChoice: typeof import('./src/components/Questionare/RadioChoice.vue')['default']
    RecommendProducts: typeof import('./src/components/Home/RecommendProducts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sample: typeof import('./src/components/sample.vue')['default']
    TopCar: typeof import('./src/components/Home/TopCar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
